### ISSUE TITLE
Meld Stake Pools Listing as Unknown in Daedalus 

### ISSUE THREAD

**Issue by ssoto2** [MELD-labs/MELD-Stake-Pools#1]
This was initially reported in the IOHK github repo for Daedalus. After reviewing the Daedalus team has pointed out it is due to a pool error and there would need to be a configuration change on the meld side

https://github.com/input-output-hk/daedalus/issues/2729

**Comment by kk-hainq** [comment]
Thank you for the report, I've replied in the referenced thread!

**Comment by kk-hainq** [comment]
Confirmed on the referenced issue.
